name: studio_lab
description: A flutter application for CBSystems S.R.L.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  f_logs:
  flutter_bloc: ^7.0.0
  flutter_email_sender: ^5.0.0
  flutter_secure_storage: ^4.1.0
  get_it: ^6.0.0
  intl: ^0.17.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  google_sign_in: ^5.0.2
  fancy_bottom_navigation: ^0.3.3
  dartz: ^0.9.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
  integration_test: ^1.0.2+2

flutter:
  uses-material-design: true
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
  assets:
    - assets/images/
